
select HISTORY_ID, CAR_ID, date_format(START_DATE, "%Y-%m-%d") as START_DATE, date_format(END_DATE, "%Y-%m-%d") as END_DATE, if(DATEDIFF(END_DATE, START_DATE) + 1 >= 30, "장기 대여", "단기 대여") as RENT_TYPE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
where EXTRACT(YEAR_MONTH FROM START_DATE) = 202209
ORDER BY HISTORY_ID DESC;
