SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
from member_profile
WHERE TLNO IS NOT NULL
AND GENDER='W'
AND DATE_FORMAT(DATE_OF_BIRTH, '%m')=03
ORDER BY MEMBER_ID ASC